name: CI Build and Test

on:
  push:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      run: |
        docker build -t clang18-ubuntu:latest .
        
    - name: Make run.sh executable
      run: |
        chmod +x run.sh
        
    - name: Run tests in container
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          clang18-ubuntu:latest \
          bash -c "./run.sh"
          
    - name: Archive build artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          build/
          !build/**/*.o
          !build/**/*.a
        retention-days: 30
